Repository OCA/event, pull requests merged in 2019-06, with the labels that each got.

#140 [12.0] event_session_registration_multi_qty: Migration to 12.0
  event_session_registration_multi_qty/README.rst
  event_session_registration_multi_qty/__init__.py
  event_session_registration_multi_qty/__manifest__.py
  event_session_registration_multi_qty/models/__init__.py
  event_session_registration_multi_qty/models/event_session.py
  event_session_registration_multi_qty/readme/CONTRIBUTORS.rst
  event_session_registration_multi_qty/readme/DESCRIPTION.rst
  event_session_registration_multi_qty/readme/USAGE.rst
  event_session_registration_multi_qty/static/description/index.html
  event_session_registration_multi_qty/tests/__init__.py
  event_session_registration_multi_qty/tests/test_event_session_registration_multi_qty.py
Labels: approved, ready to merge

#153 [12.0][MIG] event_contact
  event_contact/README.rst
  event_contact/__init__.py
  event_contact/__manifest__.py
  event_contact/i18n/es.po
  event_contact/i18n/event_contact.pot
  event_contact/models/__init__.py
  event_contact/models/event_event.py
  event_contact/models/event_type.py
  event_contact/readme/CONTRIBUTORS.rst
  event_contact/readme/DESCRIPTION.rst
  event_contact/readme/USAGE.rst
  event_contact/static/description/icon.png
  event_contact/static/description/index.html
  event_contact/tests/__init__.py
  event_contact/tests/test_event.py
  event_contact/views/event_event_view.xml
  event_contact/views/event_type_view.xml
Labels: approved

#108 [ADD] event_track_location_overlap: Control track location overlapping
  event_track_location_overlap/README.rst
  event_track_location_overlap/__init__.py
  event_track_location_overlap/__openerp__.py
  event_track_location_overlap/i18n/es.po
  event_track_location_overlap/models/__init__.py
  event_track_location_overlap/models/event_track.py
  event_track_location_overlap/models/event_track_location.py
  event_track_location_overlap/static/description/icon.png
  event_track_location_overlap/tests/__init__.py
  event_track_location_overlap/tests/test_overlap.py
  event_track_location_overlap/views/event_track_location_view.xml
Labels: enhancement, needs review

#151 12.0 mig event_project
  event_project/README.rst
  event_project/__init__.py
  event_project/__manifest__.py
  event_project/i18n/es.po
  event_project/i18n/event_project.pot
  event_project/i18n/sl.po
  event_project/models/__init__.py
  event_project/models/event_event.py
  event_project/models/project_project.py
  event_project/models/project_task.py
  event_project/readme/CONTRIBUTORS.rst
  event_project/readme/DESCRIPTION.rst
  event_project/readme/USAGE.rst
  event_project/security/ir.model.access.csv
  event_project/static/description/icon.png
  event_project/static/description/index.html
  event_project/tests/__init__.py
  event_project/tests/test_event_project.py
  event_project/views/event_event_view.xml
  event_project/views/project_project_view.xml
  event_project/views/project_task_view.xml
  oca_dependencies.txt
Labels: approved, ready to merge, work in progress
