Repository OCA/event, pull requests merged in 2019-03, with the labels that each got.

#122 12.0 partner event
  partner_event/README.rst
  partner_event/__init__.py
  partner_event/__manifest__.py
  partner_event/i18n/es.po
  partner_event/i18n/sl.po
  partner_event/models/__init__.py
  partner_event/models/event_event.py
  partner_event/models/event_registration.py
  partner_event/models/res_partner.py
  partner_event/readme/CONFIGURE.rst
  partner_event/readme/CONTRIBUTORS.rst
  partner_event/readme/DESCRIPTION.rst
  partner_event/static/description/icon.png
  partner_event/static/description/index.html
  partner_event/tests/__init__.py
  partner_event/tests/test_event_registration.py
  partner_event/views/event_event_view.xml
  partner_event/views/event_registration_view.xml
  partner_event/views/res_partner_view.xml
  partner_event/wizard/__init__.py
  partner_event/wizard/res_partner_register_event.py
  partner_event/wizard/res_partner_register_event_view.xml
Labels: needs review

#81 [10.0][ADD] event_sale_registration_multy_qty: New module
  event_sale_registration_multi_qty/README.rst
  event_sale_registration_multi_qty/__init__.py
  event_sale_registration_multi_qty/__manifest__.py
  event_sale_registration_multi_qty/i18n/es.po
  event_sale_registration_multi_qty/models/__init__.py
  event_sale_registration_multi_qty/models/sale_order.py
  event_sale_registration_multi_qty/reports/__init__.py
  event_sale_registration_multi_qty/tests/__init__.py
  event_sale_registration_multi_qty/tests/test_event_sale_registration_multi_qty.py
  event_sale_registration_multi_qty/wizards/__init__.py
  event_sale_registration_multi_qty/wizards/event_edit_registration.py
  event_sale_registration_multi_qty/wizards/event_edit_registration.xml
Labels: approved, needs review

#127 [11.0] [MIG] event_session
  event_session/README.rst
  event_session/__init__.py
  event_session/__manifest__.py
  event_session/i18n/es.po
  event_session/i18n/event_session.pot
  event_session/i18n/nl.po
  event_session/models/__init__.py
  event_session/models/event.py
  event_session/models/event_mail.py
  event_session/models/event_session.py
  event_session/models/res_config_settings.py
  event_session/security/event_session_security.xml
  event_session/security/ir.model.access.csv
  event_session/tests/__init__.py
  event_session/tests/test_session.py
  event_session/views/event_session_view.xml
  event_session/views/event_view.xml
  event_session/wizards/__init__.py
  event_session/wizards/wizard_event_session.py
  event_session/wizards/wizard_event_session_view.xml
Labels: needs review

#135 [10.0] website_event_require_login: New module
  website_event_require_login/README.rst
  website_event_require_login/__init__.py
  website_event_require_login/__manifest__.py
  website_event_require_login/controllers/__init__.py
  website_event_require_login/controllers/main.py
  website_event_require_login/i18n/es.po
  website_event_require_login/i18n/website_event_require_login.pot
  website_event_require_login/models/__init__.py
  website_event_require_login/models/event.py
  website_event_require_login/readme/CONFIGURE.rst
  website_event_require_login/readme/CONTRIBUTORS.rst
  website_event_require_login/readme/DESCRIPTION.rst
  website_event_require_login/readme/ROADMAP.rst
  website_event_require_login/readme/USAGE.rst
  website_event_require_login/static/description/index.html
  website_event_require_login/views/event_views.xml
  website_event_require_login/views/website_event_templates.xml
Labels: approved, needs review

#138 12.0 mig event registration multi qty
  event_registration_multi_qty/README.rst
  event_registration_multi_qty/__init__.py
  event_registration_multi_qty/__manifest__.py
  event_registration_multi_qty/i18n/es.po
  event_registration_multi_qty/i18n/event_registration_multi_qty.pot
  event_registration_multi_qty/models/__init__.py
  event_registration_multi_qty/models/event.py
  event_registration_multi_qty/readme/CONFIGURE.rst
  event_registration_multi_qty/readme/CONTRIBUTORS.rst
  event_registration_multi_qty/readme/DESCRIPTION.rst
  event_registration_multi_qty/readme/USAGE.rst
  event_registration_multi_qty/static/description/index.html
  event_registration_multi_qty/tests/__init__.py
  event_registration_multi_qty/tests/test_event_registration_multi_qty.py
  event_registration_multi_qty/views/event_view.xml
Labels: approved, ready to merge
