Repository OCA/event, pull requests merged in 2019-04, with the labels that each got.

#131 [12.0][MIG] website_event_filter_selector: Migration to v12
  website_event_filter_selector/README.rst
  website_event_filter_selector/__init__.py
  website_event_filter_selector/__manifest__.py
  website_event_filter_selector/controllers/__init__.py
  website_event_filter_selector/controllers/main.py
  website_event_filter_selector/demo/assets.xml
  website_event_filter_selector/demo/tour_data.xml
  website_event_filter_selector/i18n/de.po
  website_event_filter_selector/i18n/es.po
  website_event_filter_selector/models/__init__.py
  website_event_filter_selector/models/event.py
  website_event_filter_selector/readme/CONFIGURE.rst
  website_event_filter_selector/readme/CONTRIBUTORS.rst
  website_event_filter_selector/readme/DESCRIPTION.rst
  website_event_filter_selector/readme/ROADMAP.rst
  website_event_filter_selector/static/description/all.png
  website_event_filter_selector/static/description/icon.png
  website_event_filter_selector/static/description/index.html
  website_event_filter_selector/static/src/js/website_event_filter_selector.js
  website_event_filter_selector/static/src/js/website_event_filter_selector.tour.js
  website_event_filter_selector/templates/assets.xml
  website_event_filter_selector/templates/event.xml
  website_event_filter_selector/tests/__init__.py
  website_event_filter_selector/tests/test_ui.py
Labels: approved, migration

#132 [12.0][MIG] event_track_location_overlap: Migration to v12
  event_track_location_overlap/README.rst
  event_track_location_overlap/__init__.py
  event_track_location_overlap/__manifest__.py
  event_track_location_overlap/i18n/es.po
  event_track_location_overlap/models/__init__.py
  event_track_location_overlap/models/event_track.py
  event_track_location_overlap/models/event_track_location.py
  event_track_location_overlap/readme/CONFIGURE.rst
  event_track_location_overlap/readme/CONTRIBUTORS.rst
  event_track_location_overlap/readme/DESCRIPTION.rst
  event_track_location_overlap/readme/USAGE.rst
  event_track_location_overlap/static/description/icon.png
  event_track_location_overlap/tests/__init__.py
  event_track_location_overlap/tests/test_overlap.py
  event_track_location_overlap/views/event_track_location_view.xml
  requirements.txt
Labels: approved

#144 [12.0] [MIG] website_event_filter_organizer: Migration to v12
  website_event_filter_organizer/README.rst
  website_event_filter_organizer/__init__.py
  website_event_filter_organizer/__manifest__.py
  website_event_filter_organizer/controllers/__init__.py
  website_event_filter_organizer/controllers/main.py
  website_event_filter_organizer/demo/assets.xml
  website_event_filter_organizer/i18n/de.po
  website_event_filter_organizer/i18n/es.po
  website_event_filter_organizer/i18n/it.po
  website_event_filter_organizer/i18n/pt_BR.po
  website_event_filter_organizer/i18n/sl.po
  website_event_filter_organizer/i18n/website_event_filter_organizer.pot
  website_event_filter_organizer/readme/CONTRIBUTORS.rst
  website_event_filter_organizer/readme/DESCRIPTION.rst
  website_event_filter_organizer/readme/USAGE.rst
  website_event_filter_organizer/static/description/icon.png
  website_event_filter_organizer/static/description/index.html
  website_event_filter_organizer/static/src/js/tour.js
  website_event_filter_organizer/tests/__init__.py
  website_event_filter_organizer/tests/test_ui.py
  website_event_filter_organizer/views/website_event.xml
Labels: approved

#143 [MIG] event_email_reminder: Migrate to v12
  event_email_reminder/README.rst
  event_email_reminder/__init__.py
  event_email_reminder/__manifest__.py
  event_email_reminder/data/event_email_reminder_data.xml
  event_email_reminder/i18n/es.po
  event_email_reminder/models/__init__.py
  event_email_reminder/models/event.py
  event_email_reminder/readme/CONFIGURE.rst
  event_email_reminder/readme/CONTRIBUTORS.rst
  event_email_reminder/readme/CREDITS.rst
  event_email_reminder/readme/DESCRIPTION.rst
  event_email_reminder/static/description/icon.png
  event_email_reminder/static/description/index.html
  event_email_reminder/tests/__init__.py
  event_email_reminder/tests/test_event_event.py
Labels: approved, migration, ready to merge
