Repository OCA/event, pull requests merged in 2019-05, with the labels that each got.

#134 [ADD] website_event_questions_by_ticket: Conditional Events Questions
  website_event_questions_by_ticket/README.rst
  website_event_questions_by_ticket/__init__.py
  website_event_questions_by_ticket/__manifest__.py
  website_event_questions_by_ticket/models/__init__.py
  website_event_questions_by_ticket/models/event_event.py
  website_event_questions_by_ticket/readme/CONFIGURE.rst
  website_event_questions_by_ticket/readme/CONTRIBUTORS.rst
  website_event_questions_by_ticket/readme/DESCRIPTION.rst
  website_event_questions_by_ticket/readme/ROADMAP.rst
  website_event_questions_by_ticket/readme/USAGE.rst
  website_event_questions_by_ticket/static/description/index.html
  website_event_questions_by_ticket/views/event_event_views.xml
  website_event_questions_by_ticket/views/event_templates.xml
Labels: approved, needs review

#133 [ADD] website_event_questions_free_text: Free Text Answers on Events Questions
  website_event_questions_free_text/README.rst
  website_event_questions_free_text/__init__.py
  website_event_questions_free_text/__manifest__.py
  website_event_questions_free_text/controllers/__init__.py
  website_event_questions_free_text/controllers/main.py
  website_event_questions_free_text/models/__init__.py
  website_event_questions_free_text/models/event_event.py
  website_event_questions_free_text/readme/CONFIGURE.rst
  website_event_questions_free_text/readme/CONTRIBUTORS.rst
  website_event_questions_free_text/readme/DESCRIPTION.rst
  website_event_questions_free_text/readme/ROADMAP.rst
  website_event_questions_free_text/readme/USAGE.rst
  website_event_questions_free_text/security/ir.model.access.csv
  website_event_questions_free_text/static/description/index.html
  website_event_questions_free_text/views/event_event_views.xml
  website_event_questions_free_text/views/event_templates.xml
Labels: approved, needs review

#145 [12.0] event_mail: Migration to 12.0
  event_mail/README.rst
  event_mail/__init__.py
  event_mail/__manifest__.py
  event_mail/i18n/es.po
  event_mail/i18n/event_mail.pot
  event_mail/i18n/fr.po
  event_mail/models/__init__.py
  event_mail/models/event.py
  event_mail/models/event_mail.py
  event_mail/models/event_type.py
  event_mail/models/res_company.py
  event_mail/models/res_config_settings.py
  event_mail/readme/CONTRIBUTORS.rst
  event_mail/readme/DESCRIPTION.rst
  event_mail/readme/USAGE.rst
  event_mail/security/ir.model.access.csv
  event_mail/static/description/icon.png
  event_mail/static/description/index.html
  event_mail/tests/__init__.py
  event_mail/tests/test_event_mail.py
  event_mail/views/event_mail_view.xml
  event_mail/views/event_view.xml
  event_mail/views/res_config_view.xml
Labels: approved

#136 [12.0] event_session: Migration to 12.0
  event_session/README.rst
  event_session/__init__.py
  event_session/__manifest__.py
  event_session/i18n/es.po
  event_session/i18n/event_session.pot
  event_session/i18n/nl.po
  event_session/models/__init__.py
  event_session/models/event.py
  event_session/models/event_mail.py
  event_session/models/event_session.py
  event_session/models/res_config_settings.py
  event_session/readme/CONTRIBUTORS.rst
  event_session/readme/DESCRIPTION.rst
  event_session/readme/USAGE.rst
  event_session/security/event_session_security.xml
  event_session/security/ir.model.access.csv
  event_session/static/description/index.html
  event_session/tests/__init__.py
  event_session/tests/test_session.py
  event_session/views/event_session_view.xml
  event_session/views/event_view.xml
  event_session/wizards/__init__.py
  event_session/wizards/wizard_event_session.py
  event_session/wizards/wizard_event_session_view.xml
Labels: approved, ready to merge

#142 [11.0][MIG] website event require login
  website_event_require_login/README.rst
  website_event_require_login/__init__.py
  website_event_require_login/__manifest__.py
  website_event_require_login/controllers/__init__.py
  website_event_require_login/controllers/main.py
  website_event_require_login/i18n/es.po
  website_event_require_login/i18n/website_event_require_login.pot
  website_event_require_login/models/__init__.py
  website_event_require_login/models/event.py
  website_event_require_login/readme/CONFIGURE.rst
  website_event_require_login/readme/CONTRIBUTORS.rst
  website_event_require_login/readme/DESCRIPTION.rst
  website_event_require_login/readme/ROADMAP.rst
  website_event_require_login/readme/USAGE.rst
  website_event_require_login/static/description/icon.png
  website_event_require_login/static/description/index.html
  website_event_require_login/views/event_views.xml
  website_event_require_login/views/website_event_templates.xml
Labels: needs review

#147 website_event_filter_organizer: Set the correct href parameter
  website_event_filter_organizer/views/website_event.xml
Labels: approved

#148 [MIG] website_event_snippet_calendar: Migration to 12.0
  website_event_snippet_calendar/README.rst
  website_event_snippet_calendar/__init__.py
  website_event_snippet_calendar/__manifest__.py
  website_event_snippet_calendar/controllers/__init__.py
  website_event_snippet_calendar/controllers/main.py
  website_event_snippet_calendar/i18n/de.po
  website_event_snippet_calendar/i18n/es.po
  website_event_snippet_calendar/i18n/website_event_snippet_calendar.pot
  website_event_snippet_calendar/models/__init__.py
  website_event_snippet_calendar/models/event_event.py
  website_event_snippet_calendar/readme/CONTRIBUTORS.rst
  website_event_snippet_calendar/readme/DESCRIPTION.rst
  website_event_snippet_calendar/readme/USAGE.rst
  website_event_snippet_calendar/static/description/icon.png
  website_event_snippet_calendar/static/description/icon.svg
  website_event_snippet_calendar/static/description/index.html
  website_event_snippet_calendar/static/src/css/style.scss
  website_event_snippet_calendar/static/src/js/animation.js
  website_event_snippet_calendar/static/src/js/options.js
  website_event_snippet_calendar/static/src/xml/snippets.xml
  website_event_snippet_calendar/templates/assets.xml
  website_event_snippet_calendar/templates/embed.xml
  website_event_snippet_calendar/templates/snippets.xml
Labels: approved

#146 12.0 mig website_event_type_description
  website_event_type_description/README.rst
  website_event_type_description/__init__.py
  website_event_type_description/__manifest__.py
  website_event_type_description/i18n/es.po
  website_event_type_description/i18n/website_event_type_description.pot
  website_event_type_description/images/all.png
  website_event_type_description/images/seminars.png
  website_event_type_description/migrations/12.0.1.0.0/post-migration.py
  website_event_type_description/models/__init__.py
  website_event_type_description/models/event.py
  website_event_type_description/readme/CONTRIBUTORS.rst
  website_event_type_description/readme/DESCRIPTION.rst
  website_event_type_description/readme/ROADMAP.rst
  website_event_type_description/readme/USAGE.rst
  website_event_type_description/static/description/icon.png
  website_event_type_description/static/description/index.html
  website_event_type_description/views/event.xml
  website_event_type_description/views/event_type_view.xml
Labels: approved

#150 [ADD] gitignore Visual Studio .vs/
  .gitignore
Labels: approved

#137 [12.0] event_sale_session: Migration to 12.0
  event_sale_session/README.rst
  event_sale_session/__init__.py
  event_sale_session/__manifest__.py
  event_sale_session/i18n/es.po
  event_sale_session/models/__init__.py
  event_sale_session/models/account_invoice.py
  event_sale_session/models/event_event.py
  event_sale_session/models/event_registration.py
  event_sale_session/models/event_session.py
  event_sale_session/models/sale_order.py
  event_sale_session/readme/CONTRIBUTORS.rst
  event_sale_session/readme/DESCRIPTION.rst
  event_sale_session/readme/USAGE.rst
  event_sale_session/reports/__init__.py
  event_sale_session/reports/sale_report.py
  event_sale_session/reports/sale_report_views.xml
  event_sale_session/security/ir.model.access.csv
  event_sale_session/static/description/index.html
  event_sale_session/tests/__init__.py
  event_sale_session/tests/test_event_sale_session.py
  event_sale_session/views/event_session_view.xml
  event_sale_session/views/event_view.xml
  event_sale_session/views/sale_order_views.xml
  event_sale_session/wizard/__init__.py
  event_sale_session/wizard/event_edit_registration.py
  event_sale_session/wizard/event_edit_registration.xml
Labels: approved

#139 [12.0] event_sale_registration_multi_qty: Migration to 12.0
  event_sale_registration_multi_qty/README.rst
  event_sale_registration_multi_qty/__init__.py
  event_sale_registration_multi_qty/__manifest__.py
  event_sale_registration_multi_qty/i18n/es.po
  event_sale_registration_multi_qty/models/__init__.py
  event_sale_registration_multi_qty/models/sale_order.py
  event_sale_registration_multi_qty/readme/CONTRIBUTORS.rst
  event_sale_registration_multi_qty/readme/DESCRIPTION.rst
  event_sale_registration_multi_qty/readme/USAGE.rst
  event_sale_registration_multi_qty/static/description/index.html
  event_sale_registration_multi_qty/tests/__init__.py
  event_sale_registration_multi_qty/tests/test_event_sale_registration_multi_qty.py
  event_sale_registration_multi_qty/wizards/__init__.py
  event_sale_registration_multi_qty/wizards/event_edit_registration.py
  event_sale_registration_multi_qty/wizards/event_edit_registration.xml
Labels: approved
