Repository OCA/event, pull requests merged in 2020-10, with the labels that each got.

#193 [13.0][MIG] website_event_require_login: Migration to 13.0
  setup/website_event_require_login/odoo/addons/website_event_require_login
  setup/website_event_require_login/setup.py
  website_event_require_login/README.rst
  website_event_require_login/__init__.py
  website_event_require_login/__manifest__.py
  website_event_require_login/controllers/__init__.py
  website_event_require_login/controllers/main.py
  website_event_require_login/i18n/es.po
  website_event_require_login/i18n/website_event_require_login.pot
  website_event_require_login/models/__init__.py
  website_event_require_login/models/event.py
  website_event_require_login/readme/CONFIGURE.rst
  website_event_require_login/readme/CONTRIBUTORS.rst
  website_event_require_login/readme/DESCRIPTION.rst
  website_event_require_login/readme/ROADMAP.rst
  website_event_require_login/readme/USAGE.rst
  website_event_require_login/static/description/icon.png
  website_event_require_login/static/description/index.html
  website_event_require_login/views/event_views.xml
  website_event_require_login/views/website_event_templates.xml
Labels: approved, bot is merging ⏳, needs review

#196 [MIG] website_event_questions_by_ticket: Migration to 13.0
  setup/website_event_questions_by_ticket/odoo/addons/website_event_questions_by_ticket
  setup/website_event_questions_by_ticket/setup.py
  website_event_questions_by_ticket/README.rst
  website_event_questions_by_ticket/__init__.py
  website_event_questions_by_ticket/__manifest__.py
  website_event_questions_by_ticket/models/__init__.py
  website_event_questions_by_ticket/models/event_event.py
  website_event_questions_by_ticket/readme/CONFIGURE.rst
  website_event_questions_by_ticket/readme/CONTRIBUTORS.rst
  website_event_questions_by_ticket/readme/DESCRIPTION.rst
  website_event_questions_by_ticket/readme/ROADMAP.rst
  website_event_questions_by_ticket/readme/USAGE.rst
  website_event_questions_by_ticket/static/description/icon.png
  website_event_questions_by_ticket/static/description/index.html
  website_event_questions_by_ticket/tests/__init__.py
  website_event_questions_by_ticket/tests/test_ticket.py
  website_event_questions_by_ticket/views/event_event_views.xml
  website_event_questions_by_ticket/views/event_templates.xml
Labels: approved, bot is merging ⏳, ready to merge

#198 [14.0][IMP] Use strict mode in prettier xml plugin
  .prettierrc.yml
Labels: bot is merging ⏳, enhancement
