Repository OCA/event, pull requests merged in 2020-04, with the labels that each got.

#179 [MOD] 12.0 Replace code using system lang by babel dates translations
  event_session/__manifest__.py
  event_session/models/event_session.py
  event_session/tests/test_session.py
Labels: approved, bot is merging ⏳, ready to merge

#182 [FIX] website_event_excerpt_img: fix some bootstrap 4 styles
  website_event_excerpt_img/views/event.xml
Labels: bot is merging ⏳, bug

#183 [IMP] website_event_filter_selector: simpler automatic width
  website_event_filter_selector/templates/event.xml
Labels: approved, bot is merging ⏳, enhancement

#185 [FIX] website_event_snippet_calendar: BS4 styles
  website_event_snippet_calendar/static/src/xml/snippets.xml
Labels: bot is merging ⏳, bug

#184 [IMP] website_event_filter_selector: make prettier
  website_event_excerpt_img/views/event.xml
  website_event_filter_selector/templates/event.xml
Labels: approved, bot is merging ⏳, enhancement
