Repository OCA/event, pull requests merged in 2021-12, with the labels that each got.

#246 [12.0][FIX] website_event_crm: Take into account multiwebsite environments
  website_event_crm/README.rst
  website_event_crm/models/crm_lead.py
  website_event_crm/readme/CONTRIBUTORS.rst
  website_event_crm/static/description/index.html
Labels: approved, bot is merging ⏳

#243 [13.0][MIG] website_event_crm: Migration to 13.0
  setup/website_event_crm/odoo/addons/website_event_crm
  setup/website_event_crm/setup.py
  website_event_crm/README.rst
  website_event_crm/__init__.py
  website_event_crm/__manifest__.py
  website_event_crm/data/ir_cron_data.xml
  website_event_crm/data/mail_template_data.xml
  website_event_crm/i18n/es.po
  website_event_crm/i18n/website_event_crm.pot
  website_event_crm/models/__init__.py
  website_event_crm/models/crm_lead.py
  website_event_crm/models/crm_stage.py
  website_event_crm/models/event_type.py
  website_event_crm/readme/CONFIGURE.rst
  website_event_crm/readme/CONTRIBUTORS.rst
  website_event_crm/readme/DESCRIPTION.rst
  website_event_crm/readme/INSTALL.rst
  website_event_crm/readme/USAGE.rst
  website_event_crm/static/description/icon.png
  website_event_crm/static/description/index.html
  website_event_crm/views/crm_lead_view.xml
  website_event_crm/views/crm_stage_view.xml
  website_event_crm/wizards/__init__.py
  website_event_crm/wizards/mail_compose_message.py
Labels: bot is merging ⏳

#238 [14.0][MIG] event_mail: Migration to 14.0
  event_mail/README.rst
  event_mail/__init__.py
  event_mail/__manifest__.py
  event_mail/i18n/es.po
  event_mail/i18n/event_mail.pot
  event_mail/i18n/fr.po
  event_mail/models/__init__.py
  event_mail/models/event.py
  event_mail/models/event_mail.py
  event_mail/models/event_type.py
  event_mail/models/res_company.py
  event_mail/models/res_config_settings.py
  event_mail/readme/CONTRIBUTORS.rst
  event_mail/readme/DESCRIPTION.rst
  event_mail/readme/USAGE.rst
  event_mail/security/ir.model.access.csv
  event_mail/static/description/icon.png
  event_mail/static/description/index.html
  event_mail/tests/__init__.py
  event_mail/tests/test_event_mail.py
  event_mail/views/event_mail_view.xml
  event_mail/views/event_view.xml
  event_mail/views/res_config_view.xml
  setup/event_mail/odoo/addons/event_mail
  setup/event_mail/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#249 [14.0][MIG] event_registration_mass_mailing: Migration to 14.0
  event_registration_mass_mailing/README.rst
  event_registration_mass_mailing/__init__.py
  event_registration_mass_mailing/__manifest__.py
  event_registration_mass_mailing/i18n/es.po
  event_registration_mass_mailing/i18n/event_registration_mass_mailing.pot
  event_registration_mass_mailing/i18n/fr.po
  event_registration_mass_mailing/readme/CONTRIBUTORS.rst
  event_registration_mass_mailing/readme/DESCRIPTION.rst
  event_registration_mass_mailing/readme/USAGE.rst
  event_registration_mass_mailing/security/ir.model.access.csv
  event_registration_mass_mailing/static/description/icon.png
  event_registration_mass_mailing/static/description/index.html
  event_registration_mass_mailing/tests/__init__.py
  event_registration_mass_mailing/tests/test_event_registration_mail_list_wizard.py
  event_registration_mass_mailing/views/event_registration.xml
  event_registration_mass_mailing/wizard/__init__.py
  event_registration_mass_mailing/wizard/event_registration_mail_list_wizard.py
  event_registration_mass_mailing/wizard/event_registration_mail_list_wizard.xml
  setup/event_registration_mass_mailing/odoo/addons/event_registration_mass_mailing
  setup/event_registration_mass_mailing/setup.py
Labels: approved, bot is merging ⏳
