Repository OCA/event, pull requests merged in 2021-11, with the labels that each got.

#207 [14.0][MIG] partner_event: Migration to 14.0
  partner_event/README.rst
  partner_event/__init__.py
  partner_event/__manifest__.py
  partner_event/hooks.py
  partner_event/i18n/es.po
  partner_event/i18n/partner_event.pot
  partner_event/i18n/sl.po
  partner_event/models/__init__.py
  partner_event/models/event_event.py
  partner_event/models/event_registration.py
  partner_event/models/res_partner.py
  partner_event/readme/CONFIGURE.rst
  partner_event/readme/CONTRIBUTORS.rst
  partner_event/readme/DESCRIPTION.rst
  partner_event/security/ir.model.access.csv
  partner_event/static/description/icon.png
  partner_event/static/description/index.html
  partner_event/tests/__init__.py
  partner_event/tests/test_event_registration.py
  partner_event/views/event_event_view.xml
  partner_event/views/event_registration_view.xml
  partner_event/views/res_partner_view.xml
  partner_event/wizard/__init__.py
  partner_event/wizard/res_partner_register_event.py
  partner_event/wizard/res_partner_register_event_view.xml
Labels: bot is merging ⏳

#241 [14.0][MIG] website_event_questions_template: Migration to 14.0
  setup/website_event_questions_template/odoo/addons/website_event_questions_template
  setup/website_event_questions_template/setup.py
  website_event_questions_template/README.rst
  website_event_questions_template/__init__.py
  website_event_questions_template/__manifest__.py
  website_event_questions_template/i18n/es.po
  website_event_questions_template/i18n/website_event_questions_template.pot
  website_event_questions_template/models/__init__.py
  website_event_questions_template/models/event.py
  website_event_questions_template/models/event_question_template.py
  website_event_questions_template/readme/CONFIGURE.rst
  website_event_questions_template/readme/CONTRIBUTORS.rst
  website_event_questions_template/readme/DESCRIPTION.rst
  website_event_questions_template/readme/USAGE.rst
  website_event_questions_template/security/ir.model.access.csv
  website_event_questions_template/static/description/icon.png
  website_event_questions_template/static/description/index.html
  website_event_questions_template/tests/__init__.py
  website_event_questions_template/tests/test_website_event_questions_template.py
  website_event_questions_template/views/event_view.xml
  website_event_questions_template/views/website_event_questions_template_view.xml
Labels: approved, bot is merging ⏳

#240 [13.0][MIG] crm_event: Migration to 13.0
  crm_event/README.rst
  crm_event/__init__.py
  crm_event/__manifest__.py
  crm_event/i18n/crm_event.pot
  crm_event/i18n/es.po
  crm_event/models/__init__.py
  crm_event/models/crm_lead.py
  crm_event/models/event_type.py
  crm_event/readme/CONFIGURE.rst
  crm_event/readme/CONTRIBUTORS.rst
  crm_event/readme/DESCRIPTION.rst
  crm_event/readme/USAGE.rst
  crm_event/reports/__init__.py
  crm_event/reports/event_type_report.py
  crm_event/reports/event_type_report_view.xml
  crm_event/security/ir.model.access.csv
  crm_event/static/description/icon.png
  crm_event/static/description/index.html
  crm_event/tests/__init__.py
  crm_event/tests/test_event_type.py
  crm_event/views/crm_lead_view.xml
  crm_event/views/event_type_view.xml
  setup/crm_event/odoo/addons/crm_event
  setup/crm_event/setup.py
Labels: approved, migration, bot is merging ⏳

#204 [ADD] sale_crm_event_reservation: sell events like a boss
  .travis.yml
  sale_crm_event_reservation/README.rst
  sale_crm_event_reservation/__init__.py
  sale_crm_event_reservation/__manifest__.py
  sale_crm_event_reservation/i18n/es.po
  sale_crm_event_reservation/i18n/sale_crm_event_reservation.pot
  sale_crm_event_reservation/readme/CONFIGURE.rst
  sale_crm_event_reservation/readme/CONTRIBUTORS.rst
  sale_crm_event_reservation/readme/DESCRIPTION.rst
  sale_crm_event_reservation/readme/INSTALL.rst
  sale_crm_event_reservation/readme/USAGE.rst
  sale_crm_event_reservation/reports/__init__.py
  sale_crm_event_reservation/reports/event_type_report.py
  sale_crm_event_reservation/reports/event_type_report_views.xml
  sale_crm_event_reservation/static/description/icon.png
  sale_crm_event_reservation/static/description/index.html
  sale_crm_event_reservation/tests/__init__.py
  sale_crm_event_reservation/tests/test_wizard.py
  sale_crm_event_reservation/views/crm_lead_views.xml
  sale_crm_event_reservation/wizards/__init__.py
  sale_crm_event_reservation/wizards/crm_lead_event_sale_wizard.py
  sale_crm_event_reservation/wizards/crm_lead_event_sale_wizard_views.xml
Labels: enhancement, approved, ready to merge, bot is merging ⏳
