Repository OCA/event, pull requests merged in 2021-05, with the labels that each got.

#212 [ADD] website_event_sale_b2x_alt_price: alt B2C/B2B price on website events
  oca_dependencies.txt
  website_event_sale_b2x_alt_price/README.rst
  website_event_sale_b2x_alt_price/__init__.py
  website_event_sale_b2x_alt_price/__manifest__.py
  website_event_sale_b2x_alt_price/models/__init__.py
  website_event_sale_b2x_alt_price/models/event_ticket.py
  website_event_sale_b2x_alt_price/readme/CONTRIBUTORS.rst
  website_event_sale_b2x_alt_price/readme/DESCRIPTION.rst
  website_event_sale_b2x_alt_price/readme/ROADMAP.rst
  website_event_sale_b2x_alt_price/readme/USAGE.rst
  website_event_sale_b2x_alt_price/static/description/icon.png
  website_event_sale_b2x_alt_price/static/description/index.html
  website_event_sale_b2x_alt_price/templates/website_event_sale.xml
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge

#209 [13.0][MIG] event_contact
  event_contact/README.rst
  event_contact/__init__.py
  event_contact/__manifest__.py
  event_contact/i18n/es.po
  event_contact/i18n/event_contact.pot
  event_contact/models/__init__.py
  event_contact/models/event_event.py
  event_contact/models/event_type.py
  event_contact/readme/CONTRIBUTORS.rst
  event_contact/readme/DESCRIPTION.rst
  event_contact/readme/USAGE.rst
  event_contact/static/description/icon.png
  event_contact/static/description/index.html
  event_contact/tests/__init__.py
  event_contact/tests/test_event.py
  event_contact/views/event_event_view.xml
  event_contact/views/event_type_view.xml
  setup/event_contact/odoo/addons/event_contact
  setup/event_contact/setup.py
Labels: approved, bot is merging ⏳, needs review

#216 [FIX] partner_event: create registrations from attendees
  partner_event/wizard/res_partner_register_event.py
Labels: bot is merging ⏳

#219 [13.0][FIX] event_session: Error when seats_max is 0
  event_session/models/event_session.py
Labels: approved, bot is merging ⏳
