Repository OCA/event, pull requests merged in 2021-08, with the labels that each got.

#229 [FIX] website_event_filter_selector: ignore events from other websites
  website_event_filter_selector/controllers/main.py
Labels: approved, bot is merging ⏳, bug

#230 [13.0][FIX] website_event_filter_selector: ignore events from other websites
  website_event_filter_city/__manifest__.py
  website_event_filter_city/controllers/main.py
Labels: bot is merging ⏳

#227 [14.0][MIG] website_event_require_login: Migration to v14
  website_event_require_login/README.rst
  website_event_require_login/__init__.py
  website_event_require_login/__manifest__.py
  website_event_require_login/controllers/__init__.py
  website_event_require_login/controllers/main.py
  website_event_require_login/i18n/es.po
  website_event_require_login/i18n/website_event_require_login.pot
  website_event_require_login/models/__init__.py
  website_event_require_login/models/event.py
  website_event_require_login/readme/CONFIGURE.rst
  website_event_require_login/readme/CONTRIBUTORS.rst
  website_event_require_login/readme/DESCRIPTION.rst
  website_event_require_login/readme/ROADMAP.rst
  website_event_require_login/readme/USAGE.rst
  website_event_require_login/static/description/icon.png
  website_event_require_login/static/description/index.html
  website_event_require_login/views/event_views.xml
  website_event_require_login/views/website_event_templates.xml
Labels: approved, ready to merge, bot is merging ⏳
