Repository OCA/event, pull requests merged in 2022-02, with the labels that each got.

#235 [V12][FIX]Check User ACL on registration to prevent ACL exception
  partner_event/views/res_partner_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#254 [13.0][MIG] event_sale_reservation: Migration to 13.0
  event_sale_registration_multi_qty/models/sale_order.py
  event_sale_registration_multi_qty/wizards/event_edit_registration.py
  event_sale_reservation/README.rst
  event_sale_reservation/__init__.py
  event_sale_reservation/__manifest__.py
  event_sale_reservation/exceptions.py
  event_sale_reservation/i18n/es.po
  event_sale_reservation/i18n/event_sale_reservation.pot
  event_sale_reservation/models/__init__.py
  event_sale_reservation/models/event_type.py
  event_sale_reservation/models/product_template.py
  event_sale_reservation/models/sale_order.py
  event_sale_reservation/models/sale_order_line.py
  event_sale_reservation/readme/CONFIGURE.rst
  event_sale_reservation/readme/CONTRIBUTORS.rst
  event_sale_reservation/readme/DESCRIPTION.rst
  event_sale_reservation/readme/INSTALL.rst
  event_sale_reservation/readme/ROADMAP.rst
  event_sale_reservation/readme/USAGE.rst
  event_sale_reservation/reports/__init__.py
  event_sale_reservation/reports/sale_report.py
  event_sale_reservation/reports/sale_report_view.xml
  event_sale_reservation/static/description/icon.png
  event_sale_reservation/static/description/index.html
  event_sale_reservation/tests/__init__.py
  event_sale_reservation/tests/test_event_sale.py
  event_sale_reservation/views/event_type_view.xml
  event_sale_reservation/views/product_template_view.xml
  event_sale_reservation/views/sale_order_view.xml
  event_sale_reservation/wizards/__init__.py
  event_sale_reservation/wizards/registration_editor.py
  event_sale_reservation/wizards/registration_editor_line.py
  event_sale_reservation/wizards/registration_editor_view.xml
  setup/event_sale_reservation/odoo/addons/event_sale_reservation
  setup/event_sale_reservation/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#236 [ADD] module website_event_sale_hide_ticket
  setup/website_event_sale_hide_ticket/odoo/addons/website_event_sale_hide_ticket
  setup/website_event_sale_hide_ticket/setup.py
  website_event_sale_hide_ticket/README.rst
  website_event_sale_hide_ticket/__init__.py
  website_event_sale_hide_ticket/__manifest__.py
  website_event_sale_hide_ticket/models/__init__.py
  website_event_sale_hide_ticket/models/event_event.py
  website_event_sale_hide_ticket/models/event_ticket.py
  website_event_sale_hide_ticket/readme/CONFIGURE.rst
  website_event_sale_hide_ticket/readme/CONTRIBUTORS.rst
  website_event_sale_hide_ticket/readme/DESCRIPTION.rst
  website_event_sale_hide_ticket/templates/event_ticket.xml
  website_event_sale_hide_ticket/views/event_ticket.xml
Labels: approved, bot is merging ⏳

#256 [13.0][MIG] sale_crm_event_reservation: Migration to 13.0
  sale_crm_event_reservation/README.rst
  sale_crm_event_reservation/__init__.py
  sale_crm_event_reservation/__manifest__.py
  sale_crm_event_reservation/i18n/es.po
  sale_crm_event_reservation/i18n/sale_crm_event_reservation.pot
  sale_crm_event_reservation/readme/CONFIGURE.rst
  sale_crm_event_reservation/readme/CONTRIBUTORS.rst
  sale_crm_event_reservation/readme/DESCRIPTION.rst
  sale_crm_event_reservation/readme/INSTALL.rst
  sale_crm_event_reservation/readme/USAGE.rst
  sale_crm_event_reservation/reports/__init__.py
  sale_crm_event_reservation/reports/event_type_report.py
  sale_crm_event_reservation/reports/event_type_report_views.xml
  sale_crm_event_reservation/static/description/icon.png
  sale_crm_event_reservation/static/description/index.html
  sale_crm_event_reservation/tests/__init__.py
  sale_crm_event_reservation/tests/test_wizard.py
  sale_crm_event_reservation/views/crm_lead_views.xml
  sale_crm_event_reservation/wizards/__init__.py
  sale_crm_event_reservation/wizards/crm_lead_event_sale_wizard.py
  sale_crm_event_reservation/wizards/crm_lead_event_sale_wizard_views.xml
  setup/sale_crm_event_reservation/odoo/addons/sale_crm_event_reservation
  setup/sale_crm_event_reservation/setup.py
Labels: bot is merging ⏳
