Repository OCA/event, pull requests merged in 2022-04, with the labels that each got.

#270 [14.0][MIG] event_registration_cancel_reason: Migration to 14.0
  event_registration_cancel_reason/README.rst
  event_registration_cancel_reason/__init__.py
  event_registration_cancel_reason/__manifest__.py
  event_registration_cancel_reason/i18n/es.po
  event_registration_cancel_reason/i18n/event_registration_cancel_reason.pot
  event_registration_cancel_reason/models/__init__.py
  event_registration_cancel_reason/models/event_registration.py
  event_registration_cancel_reason/readme/CONFIGURE.rst
  event_registration_cancel_reason/readme/CONTRIBUTORS.rst
  event_registration_cancel_reason/readme/DESCRIPTION.rst
  event_registration_cancel_reason/readme/USAGE.rst
  event_registration_cancel_reason/security/ir.model.access.csv
  event_registration_cancel_reason/static/description/icon.png
  event_registration_cancel_reason/static/description/index.html
  event_registration_cancel_reason/tests/__init__.py
  event_registration_cancel_reason/tests/test_event_registration_cancel_reason.py
  event_registration_cancel_reason/views/event_registration_view.xml
  event_registration_cancel_reason/wizard/__init__.py
  event_registration_cancel_reason/wizard/event_registration_cancel_log_reason.py
  event_registration_cancel_reason/wizard/event_registration_cancel_log_reason_view.xml
  setup/event_registration_cancel_reason/odoo/addons/event_registration_cancel_reason
  setup/event_registration_cancel_reason/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#255 [15.0][ADD] event_registration_qr_code
  event_registration_qr_code/README.rst
  event_registration_qr_code/__init__.py
  event_registration_qr_code/__manifest__.py
  event_registration_qr_code/models/__init__.py
  event_registration_qr_code/models/event_registration.py
  event_registration_qr_code/readme/CONTRIBUTORS.rst
  event_registration_qr_code/readme/DESCRIPTION.rst
  event_registration_qr_code/reports/report_templates.xml
  event_registration_qr_code/tests/__init__.py
  event_registration_qr_code/tests/test_event_registration_qr_code.py
  event_registration_qr_code/views/event_registration.xml
  setup/event_registration_qr_code/odoo/addons/event_registration_qr_code
  setup/event_registration_qr_code/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#267 [MIG] event_session_registration_multi_qty: Migration to 14.0
  event_session_registration_multi_qty/README.rst
  event_session_registration_multi_qty/__init__.py
  event_session_registration_multi_qty/__manifest__.py
  event_session_registration_multi_qty/i18n/event_session_registration_multi_qty.pot
  event_session_registration_multi_qty/models/__init__.py
  event_session_registration_multi_qty/models/event_session.py
  event_session_registration_multi_qty/readme/CONTRIBUTORS.rst
  event_session_registration_multi_qty/readme/DESCRIPTION.rst
  event_session_registration_multi_qty/readme/USAGE.rst
  event_session_registration_multi_qty/static/description/icon.png
  event_session_registration_multi_qty/static/description/index.html
  event_session_registration_multi_qty/tests/__init__.py
  event_session_registration_multi_qty/tests/test_event_session_registration_multi_qty.py
  setup/event_session_registration_multi_qty/odoo/addons/event_session_registration_multi_qty
  setup/event_session_registration_multi_qty/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#266 [MIG] event_sale_registration_multi_qty: Migration to 14.0
  event_registration_multi_qty/models/event.py
  event_sale_registration_multi_qty/README.rst
  event_sale_registration_multi_qty/__init__.py
  event_sale_registration_multi_qty/__manifest__.py
  event_sale_registration_multi_qty/i18n/es.po
  event_sale_registration_multi_qty/i18n/event_sale_registration_multi_qty.pot
  event_sale_registration_multi_qty/models/__init__.py
  event_sale_registration_multi_qty/models/event_registration.py
  event_sale_registration_multi_qty/models/sale_order.py
  event_sale_registration_multi_qty/readme/CONTRIBUTORS.rst
  event_sale_registration_multi_qty/readme/DESCRIPTION.rst
  event_sale_registration_multi_qty/readme/USAGE.rst
  event_sale_registration_multi_qty/static/description/icon.png
  event_sale_registration_multi_qty/static/description/index.html
  event_sale_registration_multi_qty/tests/__init__.py
  event_sale_registration_multi_qty/tests/test_event_sale_registration_multi_qty.py
  event_sale_registration_multi_qty/wizards/__init__.py
  event_sale_registration_multi_qty/wizards/event_edit_registration.py
  event_sale_registration_multi_qty/wizards/event_edit_registration.xml
  setup/event_sale_registration_multi_qty/odoo/addons/event_sale_registration_multi_qty
  setup/event_sale_registration_multi_qty/setup.py
Labels: approved, bot is merging ⏳

#272 [13.0][IMP] crm_event: Promote module to stable
  crm_event/__manifest__.py
  sale_crm_event_reservation/__manifest__.py
Labels: bot is merging ⏳

#262 [13.0][FIX] website_event_filter_city: search input
  website_event_filter_city/controllers/main.py
  website_event_filter_city/models/event.py
  website_event_filter_city/static/src/js/website_event_filter_city.tour.js
Labels: approved, bot is merging ⏳

#269 [FIX] website_event_crm: another company's event
  crm_event/tests/test_event_type.py
  website_event_crm/data/mail_template_data.xml
  website_event_crm/models/crm_lead.py
  website_event_crm/tests/__init__.py
  website_event_crm/tests/test_website_event_crm.py
  website_event_crm/views/crm_lead_view.xml
Labels: needs review, approved, bot is merging ⏳
