Repository OCA/event, pull requests merged in 2022-08, with the labels that each got.

#271 [14.0][MIG] event_registration_partner_unique: Migration to version 14.0
  event_registration_partner_unique/README.rst
  event_registration_partner_unique/__init__.py
  event_registration_partner_unique/__manifest__.py
  event_registration_partner_unique/i18n/es.po
  event_registration_partner_unique/i18n/event_registration_partner_unique.pot
  event_registration_partner_unique/models/__init__.py
  event_registration_partner_unique/models/event.py
  event_registration_partner_unique/readme/CONTRIBUTORS.rst
  event_registration_partner_unique/readme/DESCRIPTION.rst
  event_registration_partner_unique/readme/ROADMAP.rst
  event_registration_partner_unique/readme/USAGE.rst
  event_registration_partner_unique/static/description/icon.png
  event_registration_partner_unique/static/description/index.html
  event_registration_partner_unique/tests/__init__.py
  event_registration_partner_unique/tests/test_event.py
  event_registration_partner_unique/views/event_event_view.xml
  setup/event_registration_partner_unique/odoo/addons/event_registration_partner_unique
  setup/event_registration_partner_unique/setup.py
Labels: needs review, bot is merging ⏳

#280 [14.0][FIX] event_registration_partner_unique: improve README
  event_registration_partner_unique/readme/DESCRIPTION.rst
  event_registration_partner_unique/readme/USAGE.rst
Labels: bot is merging ⏳

#218 [13.0][ADD] event_registration_lang
  event_registration_lang/README.rst
  event_registration_lang/__init__.py
  event_registration_lang/__manifest__.py
  event_registration_lang/hooks.py
  event_registration_lang/models/__init__.py
  event_registration_lang/models/event_registration.py
  event_registration_lang/readme/CONTRIBUTORS.rst
  event_registration_lang/readme/DESCRIPTION.rst
  event_registration_lang/tests/__init__.py
  event_registration_lang/tests/test_event_registration_lang.py
  event_registration_lang/views/event_registration.xml
  setup/event_registration_lang/odoo/addons/event_registration_lang
  setup/event_registration_lang/setup.py
Labels: needs review, bot is merging ⏳, stale

#257 [15.0][ADD] event_registration_mail_compose
  event_registration_mail_compose/README.rst
  event_registration_mail_compose/__init__.py
  event_registration_mail_compose/__manifest__.py
  event_registration_mail_compose/i18n/fr.po
  event_registration_mail_compose/readme/CONTRIBUTORS.rst
  event_registration_mail_compose/readme/DESCRIPTION.rst
  event_registration_mail_compose/views/event_registration.xml
  setup/event_registration_mail_compose/odoo/addons/event_registration_mail_compose
  setup/event_registration_mail_compose/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳, stale

#260 [15.0][ADD] website_event_sale_cart_quantity_readonly
  setup/website_event_sale_cart_quantity_readonly/odoo/addons/website_event_sale_cart_quantity_readonly
  setup/website_event_sale_cart_quantity_readonly/setup.py
  website_event_sale_cart_quantity_readonly/__manifest__.py
  website_event_sale_cart_quantity_readonly/readme/CONTRIBUTORS.rst
  website_event_sale_cart_quantity_readonly/readme/DESCRIPTION.rst
  website_event_sale_cart_quantity_readonly/templates/cart.xml
Labels: needs review, approved, ready to merge, bot is merging ⏳, stale
