Repository OCA/event, pull requests merged in 2023-07, with the labels that each got.

#318 [16.0][MIG] event_registration_multi_qty: Migration to version 16.0
  event_registration_multi_qty/README.rst
  event_registration_multi_qty/__init__.py
  event_registration_multi_qty/__manifest__.py
  event_registration_multi_qty/i18n/es.po
  event_registration_multi_qty/i18n/event_registration_multi_qty.pot
  event_registration_multi_qty/i18n/it.po
  event_registration_multi_qty/models/__init__.py
  event_registration_multi_qty/models/event.py
  event_registration_multi_qty/readme/CONFIGURE.rst
  event_registration_multi_qty/readme/CONTRIBUTORS.rst
  event_registration_multi_qty/readme/DESCRIPTION.rst
  event_registration_multi_qty/readme/USAGE.rst
  event_registration_multi_qty/static/description/icon.png
  event_registration_multi_qty/static/description/index.html
  event_registration_multi_qty/tests/__init__.py
  event_registration_multi_qty/tests/test_event_registration_multi_qty.py
  event_registration_multi_qty/views/event_view.xml
  setup/event_registration_multi_qty/odoo/addons/event_registration_multi_qty
  setup/event_registration_multi_qty/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#328 [15.0] [FIX] event_session: regular event mail schedulers
  event_session/models/event_registration.py
Labels: approved, bot is merging ⏳

#307 [15.0][MIG] website_event_questions_by_ticket: Migration to version 15.0
  setup/website_event_questions_by_ticket/odoo/addons/website_event_questions_by_ticket
  setup/website_event_questions_by_ticket/setup.py
  website_event_questions_by_ticket/README.rst
  website_event_questions_by_ticket/__init__.py
  website_event_questions_by_ticket/__manifest__.py
  website_event_questions_by_ticket/i18n/es.po
  website_event_questions_by_ticket/i18n/it.po
  website_event_questions_by_ticket/i18n/website_event_questions_by_ticket.pot
  website_event_questions_by_ticket/models/__init__.py
  website_event_questions_by_ticket/models/event_event.py
  website_event_questions_by_ticket/readme/CONFIGURE.rst
  website_event_questions_by_ticket/readme/CONTRIBUTORS.rst
  website_event_questions_by_ticket/readme/DESCRIPTION.rst
  website_event_questions_by_ticket/readme/ROADMAP.rst
  website_event_questions_by_ticket/readme/USAGE.rst
  website_event_questions_by_ticket/static/description/icon.png
  website_event_questions_by_ticket/static/description/index.html
  website_event_questions_by_ticket/tests/__init__.py
  website_event_questions_by_ticket/tests/test_ticket.py
  website_event_questions_by_ticket/views/event_event_views.xml
  website_event_questions_by_ticket/views/event_templates.xml
Labels: bot is merging ⏳

#325 [16.0][MIG] event_session: Migration to version 16.0
  event_session/README.rst
  event_session/__init__.py
  event_session/__manifest__.py
  event_session/controllers/__init__.py
  event_session/controllers/main.py
  event_session/data/event_session_timeslot.xml
  event_session/data/mail_template.xml
  event_session/demo/event_session.xml
  event_session/i18n/es.po
  event_session/i18n/event_session.pot
  event_session/i18n/fr.po
  event_session/i18n/nl.po
  event_session/models/__init__.py
  event_session/models/event_event.py
  event_session/models/event_mail.py
  event_session/models/event_mail_registration.py
  event_session/models/event_mail_session.py
  event_session/models/event_registration.py
  event_session/models/event_session.py
  event_session/models/event_session_timeslot.py
  event_session/models/event_type.py
  event_session/readme/CONTRIBUTORS.rst
  event_session/readme/DESCRIPTION.rst
  event_session/readme/ROADMAP.rst
  event_session/readme/USAGE.rst
  event_session/reports/event_report_templates.xml
  event_session/security/ir.model.access.csv
  event_session/security/security.xml
  event_session/static/description/icon.png
  event_session/static/description/index.html
  event_session/tests/__init__.py
  event_session/tests/common.py
  event_session/tests/test_event_session.py
  event_session/tests/test_event_session_ics.py
  event_session/tests/test_event_session_mail.py
  event_session/tests/test_event_session_wizard.py
  event_session/views/event_event.xml
  event_session/views/event_registration.xml
  event_session/views/event_session.xml
  event_session/views/event_type.xml
  event_session/wizards/__init__.py
  event_session/wizards/wizard_event_session.py
  event_session/wizards/wizard_event_session.xml
  setup/event_session/odoo/addons/event_session
  setup/event_session/setup.py
Labels: bot is merging ⏳

#333 [16.0][MIG] event_sale_session: Migration to version 16.0
  event_sale_session/README.rst
  event_sale_session/__init__.py
  event_sale_session/__manifest__.py
  event_sale_session/demo/event_session.xml
  event_sale_session/i18n/es.po
  event_sale_session/i18n/event_sale_session.pot
  event_sale_session/models/__init__.py
  event_sale_session/models/event_registration.py
  event_sale_session/models/event_session.py
  event_sale_session/models/sale_order_line.py
  event_sale_session/readme/CONTRIBUTORS.rst
  event_sale_session/readme/DESCRIPTION.rst
  event_sale_session/readme/USAGE.rst
  event_sale_session/reports/__init__.py
  event_sale_session/reports/event_sale_report.py
  event_sale_session/reports/event_sale_report.xml
  event_sale_session/reports/sale_report.py
  event_sale_session/reports/sale_report.xml
  event_sale_session/static/description/icon.png
  event_sale_session/static/description/index.html
  event_sale_session/static/src/js/EventConfiguratorFormController.esm.js
  event_sale_session/tests/__init__.py
  event_sale_session/tests/test_event_sale_session.py
  event_sale_session/views/event_session.xml
  event_sale_session/views/sale_order.xml
  event_sale_session/wizard/__init__.py
  event_sale_session/wizard/event_configurator.py
  event_sale_session/wizard/event_configurator.xml
  event_sale_session/wizard/event_edit_registration.py
  event_sale_session/wizard/event_edit_registration.xml
  setup/event_sale_session/odoo/addons/event_sale_session
  setup/event_sale_session/setup.py
Labels: approved, bot is merging ⏳

#332 [16.0][MIG] event_session_registration_multi_qty: Migration to version 16.0
  event_session_registration_multi_qty/README.rst
  event_session_registration_multi_qty/__init__.py
  event_session_registration_multi_qty/__manifest__.py
  event_session_registration_multi_qty/i18n/es.po
  event_session_registration_multi_qty/i18n/event_session_registration_multi_qty.pot
  event_session_registration_multi_qty/i18n/it.po
  event_session_registration_multi_qty/models/__init__.py
  event_session_registration_multi_qty/models/event_session.py
  event_session_registration_multi_qty/readme/CONTRIBUTORS.rst
  event_session_registration_multi_qty/readme/DESCRIPTION.rst
  event_session_registration_multi_qty/readme/USAGE.rst
  event_session_registration_multi_qty/static/description/icon.png
  event_session_registration_multi_qty/static/description/index.html
  event_session_registration_multi_qty/tests/__init__.py
  event_session_registration_multi_qty/tests/test_event_session_registration_multi_qty.py
  setup/event_session_registration_multi_qty/odoo/addons/event_session_registration_multi_qty
  setup/event_session_registration_multi_qty/setup.py
Labels: approved, bot is merging ⏳
