Repository OCA/event, pull requests merged in 2024-11, with the labels that each got.

#407 [FIX] [16.0] website_event_contact: Allow portal users view contacts
  website_event_contact/views/event_templates_page_registration.xml
Labels: approved, bot is merging ⏳

#410 [17.0][MIG] website_event_require_login: Migration to version 17.0
  website_event_require_login/README.rst
  website_event_require_login/__init__.py
  website_event_require_login/__manifest__.py
  website_event_require_login/controllers/__init__.py
  website_event_require_login/controllers/main.py
  website_event_require_login/i18n/ca.po
  website_event_require_login/i18n/de.po
  website_event_require_login/i18n/es.po
  website_event_require_login/i18n/fr.po
  website_event_require_login/i18n/it.po
  website_event_require_login/i18n/pt.po
  website_event_require_login/i18n/website_event_require_login.pot
  website_event_require_login/models/__init__.py
  website_event_require_login/models/event.py
  website_event_require_login/pyproject.toml
  website_event_require_login/readme/CONFIGURE.md
  website_event_require_login/readme/CONTRIBUTORS.md
  website_event_require_login/readme/DESCRIPTION.md
  website_event_require_login/readme/ROADMAP.md
  website_event_require_login/readme/USAGE.md
  website_event_require_login/static/description/icon.png
  website_event_require_login/static/description/index.html
  website_event_require_login/views/event_views.xml
  website_event_require_login/views/website_event_templates.xml
Labels: approved, bot is merging ⏳

#412 [FIX] partner_event: get chosen partner even if not contact
  partner_event/README.rst
  partner_event/__manifest__.py
  partner_event/models/res_partner.py
  partner_event/static/description/index.html
  partner_event/tests/test_event_registration.py
Labels: needs review, approved, bot is merging ⏳

#411 [17.0][MIG] website_event_membership_restriction: Migration to version 17.0
  website_event_membership_restriction/README.rst
  website_event_membership_restriction/__init__.py
  website_event_membership_restriction/__manifest__.py
  website_event_membership_restriction/data/website_event_membership_info.xml
  website_event_membership_restriction/i18n/es.po
  website_event_membership_restriction/i18n/it.po
  website_event_membership_restriction/i18n/website_event_membership_restriction.pot
  website_event_membership_restriction/models/__init__.py
  website_event_membership_restriction/models/event_event.py
  website_event_membership_restriction/pyproject.toml
  website_event_membership_restriction/readme/CONFIGURE.md
  website_event_membership_restriction/readme/CONTRIBUTORS.md
  website_event_membership_restriction/readme/DESCRIPTION.md
  website_event_membership_restriction/readme/USAGE.md
  website_event_membership_restriction/static/description/icon.png
  website_event_membership_restriction/static/description/index.html
  website_event_membership_restriction/views/event_event_views.xml
  website_event_membership_restriction/views/event_templates.xml
Labels: approved, ready to merge, bot is merging ⏳

#413 [17.0][MIG] website_event_questions_by_ticket: Migration to version 17.0
  website_event_questions_by_ticket/README.rst
  website_event_questions_by_ticket/__init__.py
  website_event_questions_by_ticket/__manifest__.py
  website_event_questions_by_ticket/i18n/de.po
  website_event_questions_by_ticket/i18n/es.po
  website_event_questions_by_ticket/i18n/fr.po
  website_event_questions_by_ticket/i18n/it.po
  website_event_questions_by_ticket/i18n/website_event_questions_by_ticket.pot
  website_event_questions_by_ticket/models/__init__.py
  website_event_questions_by_ticket/models/event_event.py
  website_event_questions_by_ticket/pyproject.toml
  website_event_questions_by_ticket/readme/CONFIGURE.md
  website_event_questions_by_ticket/readme/CONTRIBUTORS.md
  website_event_questions_by_ticket/readme/DESCRIPTION.md
  website_event_questions_by_ticket/readme/ROADMAP.md
  website_event_questions_by_ticket/readme/USAGE.md
  website_event_questions_by_ticket/static/description/icon.png
  website_event_questions_by_ticket/static/description/index.html
  website_event_questions_by_ticket/tests/__init__.py
  website_event_questions_by_ticket/tests/test_ticket.py
  website_event_questions_by_ticket/views/event_event_views.xml
  website_event_questions_by_ticket/views/event_templates.xml
Labels: approved, bot is merging ⏳
