Repository OCA/event, pull requests merged in 2024-05, with the labels that each got.

#367 [16.0][MIG] event_registration_qr_code: Migration to 16.0
  event_registration_qr_code/README.rst
  event_registration_qr_code/__init__.py
  event_registration_qr_code/__manifest__.py
  event_registration_qr_code/i18n/ca.po
  event_registration_qr_code/i18n/es.po
  event_registration_qr_code/i18n/event_registration_qr_code.pot
  event_registration_qr_code/i18n/fr_FR.po
  event_registration_qr_code/i18n/it.po
  event_registration_qr_code/models/__init__.py
  event_registration_qr_code/models/event_registration.py
  event_registration_qr_code/readme/CONTRIBUTORS.rst
  event_registration_qr_code/readme/DESCRIPTION.rst
  event_registration_qr_code/reports/report_templates.xml
  event_registration_qr_code/static/description/icon.png
  event_registration_qr_code/static/description/index.html
  event_registration_qr_code/tests/__init__.py
  event_registration_qr_code/tests/test_event_registration_qr_code.py
  event_registration_qr_code/views/event_registration.xml
  setup/event_registration_qr_code/odoo/addons/event_registration_qr_code
  setup/event_registration_qr_code/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#368 [16.0] [MIG] event_contact
  event_contact/README.rst
  event_contact/__init__.py
  event_contact/__manifest__.py
  event_contact/i18n/es.po
  event_contact/i18n/event_contact.pot
  event_contact/i18n/it.po
  event_contact/models/__init__.py
  event_contact/models/event_event.py
  event_contact/models/event_type.py
  event_contact/readme/CONTRIBUTORS.rst
  event_contact/readme/DESCRIPTION.rst
  event_contact/readme/USAGE.rst
  event_contact/static/description/icon.png
  event_contact/static/description/index.html
  event_contact/tests/__init__.py
  event_contact/tests/test_event.py
  event_contact/views/event_event_view.xml
  event_contact/views/event_type_view.xml
  setup/event_contact/odoo/addons/event_contact
  setup/event_contact/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#369 [16.0][FIX] event_mail: Fix Mail Scheduler view
  event_mail/views/event_mail_view.xml
Labels: approved, bot is merging ⏳

#371 [16.0][FIX] event_session: event global number of attendees
  event_session/views/event_event.xml
Labels: approved, bot is merging ⏳

#372 [16.0][IMP] event_session: seats_available_unexpected
  event_session/models/event_session.py
  event_session/tests/test_event_session.py
  event_session/views/event_session.xml
Labels: approved, bot is merging ⏳
