Repository OCA/event, pull requests merged in 2024-01, with the labels that each got.

#355 [16.0][FIX] partner_event: Don't update attendee_partner_id merging partners
  partner_event/models/event_registration.py
  partner_event/wizard/__init__.py
  partner_event/wizard/base_partner_merge_automatic_wizard.py
Labels: bot is merging ⏳

#360 [16.0][IMP] event_session: improve UX in session tree
  event_session/views/event_session.xml
Labels: approved, bot is merging ⏳

#358 [15.0][FIX] event_session: Change web_ribbon text to title to make it translatable
  event_session/views/event_session.xml
Labels: approved, bot is merging ⏳

#359 [15.0][OU] event_session: Migration script
  event_session/migrations/15.0.1.0.0/pre-migration.py
Labels: approved

#361 [16.0][FIX] event_session: Change web_ribbon text to title to make it translatable
  event_session/views/event_session.xml
Labels: approved, bot is merging ⏳
