Repository OCA/event, pull requests merged in 2024-12, with the labels that each got.

#416 [17.0][MIG] website_event_filter_city: Migration to version 17.0
  website_event_filter_city/README.rst
  website_event_filter_city/__init__.py
  website_event_filter_city/__manifest__.py
  website_event_filter_city/controllers/__init__.py
  website_event_filter_city/controllers/main.py
  website_event_filter_city/demo/tour_data.xml
  website_event_filter_city/i18n/de.po
  website_event_filter_city/i18n/es.po
  website_event_filter_city/i18n/it.po
  website_event_filter_city/i18n/website_event_filter_city.pot
  website_event_filter_city/models/__init__.py
  website_event_filter_city/models/event.py
  website_event_filter_city/pyproject.toml
  website_event_filter_city/readme/CONFIGURE.md
  website_event_filter_city/readme/CONTRIBUTORS.md
  website_event_filter_city/readme/DESCRIPTION.md
  website_event_filter_city/readme/ROADMAP.md
  website_event_filter_city/static/description/all.png
  website_event_filter_city/static/description/icon.png
  website_event_filter_city/static/description/index.html
  website_event_filter_city/static/src/js/website_event_filter_city_tour.esm.js
  website_event_filter_city/templates/event.xml
  website_event_filter_city/tests/__init__.py
  website_event_filter_city/tests/test_ui.py
Labels: approved, bot is merging ⏳

#415 [17.0][MIG] event_min_seat: Migration to version 17.0
  event_min_seat/README.rst
  event_min_seat/__init__.py
  event_min_seat/__manifest__.py
  event_min_seat/i18n/es.po
  event_min_seat/i18n/event_min_seat.pot
  event_min_seat/i18n/it.po
  event_min_seat/models/__init__.py
  event_min_seat/models/event_event.py
  event_min_seat/models/event_type.py
  event_min_seat/pyproject.toml
  event_min_seat/readme/CONTRIBUTORS.md
  event_min_seat/readme/DESCRIPTION.md
  event_min_seat/static/description/icon.png
  event_min_seat/static/description/index.html
  event_min_seat/tests/__init__.py
  event_min_seat/tests/test_event_min_seat.py
  event_min_seat/views/event_event_views.xml
  event_min_seat/views/event_type_views.xml
Labels: needs review, approved, migration, bot is merging ⏳

#417 [17.0][MIG] event_stage_cancelled: Migration to 17.0
  event_stage_cancelled/README.rst
  event_stage_cancelled/__init__.py
  event_stage_cancelled/__manifest__.py
  event_stage_cancelled/data/event_data.xml
  event_stage_cancelled/data/mail_template_data.xml
  event_stage_cancelled/i18n/es.po
  event_stage_cancelled/i18n/event_stage_cancelled.pot
  event_stage_cancelled/models/__init__.py
  event_stage_cancelled/models/event_event.py
  event_stage_cancelled/models/event_mail.py
  event_stage_cancelled/models/event_registration.py
  event_stage_cancelled/models/event_stage.py
  event_stage_cancelled/models/event_type_mail.py
  event_stage_cancelled/pyproject.toml
  event_stage_cancelled/readme/CONFIGURE.md
  event_stage_cancelled/readme/CONTEXT.md
  event_stage_cancelled/readme/CONTRIBUTORS.md
  event_stage_cancelled/readme/DESCRIPTION.md
  event_stage_cancelled/readme/ROADMAP.md
  event_stage_cancelled/readme/USAGE.md
  event_stage_cancelled/static/description/icon.png
  event_stage_cancelled/static/description/index.html
  event_stage_cancelled/tests/__init__.py
  event_stage_cancelled/tests/test_event_stage_cancelled.py
  event_stage_cancelled/views/event_event_views.xml
  event_stage_cancelled/views/event_stage_views.xml
Labels: approved, bot is merging ⏳

#419 [17.0][MIG] website_event_track_stage_cancelled: Migration to version 17.0
  website_event_track_stage_cancelled/README.rst
  website_event_track_stage_cancelled/__init__.py
  website_event_track_stage_cancelled/__manifest__.py
  website_event_track_stage_cancelled/i18n/website_event_track_stage_cancelled.pot
  website_event_track_stage_cancelled/models/__init__.py
  website_event_track_stage_cancelled/models/event_event.py
  website_event_track_stage_cancelled/pyproject.toml
  website_event_track_stage_cancelled/readme/CONFIGURE.md
  website_event_track_stage_cancelled/readme/CONTRIBUTORS.md
  website_event_track_stage_cancelled/readme/DESCRIPTION.md
  website_event_track_stage_cancelled/readme/USAGE.md
  website_event_track_stage_cancelled/static/description/icon.png
  website_event_track_stage_cancelled/static/description/index.html
Labels: approved, bot is merging ⏳

#420 [17.0][FIX] website_event_filter_city: Country filter support
  website_event_filter_city/README.rst
  website_event_filter_city/__manifest__.py
  website_event_filter_city/static/description/index.html
  website_event_filter_city/templates/event.xml
Labels: approved, merged 🎉

#422 [15.0][FIX] event_sale_reservation: Correct typo in the field
  event_sale_reservation/i18n/es.po
  event_sale_reservation/i18n/event_sale_reservation.pot
  event_sale_reservation/i18n/it.po
  event_sale_reservation/models/product_template.py
Labels: approved, bot is merging ⏳

#421 [17.0][MIG] event_sale_reservation: Migration to version 17.0
  event_sale_reservation/README.rst
  event_sale_reservation/__init__.py
  event_sale_reservation/__manifest__.py
  event_sale_reservation/exceptions.py
  event_sale_reservation/i18n/es.po
  event_sale_reservation/i18n/event_sale_reservation.pot
  event_sale_reservation/i18n/it.po
  event_sale_reservation/models/__init__.py
  event_sale_reservation/models/event_type.py
  event_sale_reservation/models/product_template.py
  event_sale_reservation/models/sale_order.py
  event_sale_reservation/models/sale_order_line.py
  event_sale_reservation/pyproject.toml
  event_sale_reservation/readme/CONFIGURE.md
  event_sale_reservation/readme/CONTRIBUTORS.md
  event_sale_reservation/readme/DESCRIPTION.md
  event_sale_reservation/readme/ROADMAP.md
  event_sale_reservation/readme/USAGE.md
  event_sale_reservation/reports/__init__.py
  event_sale_reservation/reports/sale_report.py
  event_sale_reservation/reports/sale_report_view.xml
  event_sale_reservation/static/description/icon.png
  event_sale_reservation/static/description/index.html
  event_sale_reservation/tests/__init__.py
  event_sale_reservation/tests/test_event_sale.py
  event_sale_reservation/views/event_type_view.xml
  event_sale_reservation/views/product_template_view.xml
  event_sale_reservation/views/sale_order_view.xml
  event_sale_reservation/wizards/__init__.py
  event_sale_reservation/wizards/registration_editor.py
  event_sale_reservation/wizards/registration_editor_line.py
  event_sale_reservation/wizards/registration_editor_view.xml
Labels: approved, bot is merging ⏳
