Repository OCA/event, pull requests merged in 2025-05, with the labels that each got.

#444 [17.0][FIX] partner_event: handle contacts with mobile field
  partner_event/models/event_registration.py
  partner_event/tests/test_event_registration.py
Labels: bot is merging ⏳

#443 [16.0][IMP] partner_event: search partner by linked event
  partner_event/views/res_partner_view.xml
Labels: needs review, approved, bot is merging ⏳

#451 [17.0][MIG] event_email_reminder: Migration to version 17.0
  event_email_reminder/README.rst
  event_email_reminder/__init__.py
  event_email_reminder/__manifest__.py
  event_email_reminder/data/event_stage_data.xml
  event_email_reminder/data/ir_cron_data.xml
  event_email_reminder/data/mail_template_data.xml
  event_email_reminder/i18n/es.po
  event_email_reminder/i18n/event_email_reminder.pot
  event_email_reminder/i18n/it.po
  event_email_reminder/models/__init__.py
  event_email_reminder/models/event_event.py
  event_email_reminder/models/event_stage.py
  event_email_reminder/pyproject.toml
  event_email_reminder/readme/CONFIGURE.md
  event_email_reminder/readme/CONTRIBUTORS.md
  event_email_reminder/readme/CREDITS.md
  event_email_reminder/readme/DESCRIPTION.md
  event_email_reminder/static/description/icon.png
  event_email_reminder/static/description/index.html
  event_email_reminder/tests/__init__.py
  event_email_reminder/tests/test_event_event.py
  event_email_reminder/views/event_stage_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#453 [17.0][FIX] partner_event: Avoid contact error
  partner_event/README.rst
  partner_event/readme/CONTRIBUTORS.md
  partner_event/static/description/index.html
  partner_event/views/res_partner_view.xml
Labels: approved, bot is merging ⏳
